// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Persisto.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Persisto;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class GeneratedModelTemplate : GeneratedModelTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections;\r\nusing System.Collections.Generic;\r\nusin" +
                    "g System.Linq;\r\nusing Persisto;\r\n\r\n");
            
            #line 14 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"


Func<Stack<IDbModelInfo>> getModelInfoStack = () =>
	{
		var stack = new Stack<IDbModelInfo>();
		
		var info = ModelInfo;

		while (info != null)
		{
			stack.Push(info);
			info = info.BaseModelInfo;
		}

		return stack;
	};


            
            #line default
            #line hidden
            this.Write("\r\nnamespace Persisto.Generated.Models\r\n{\r\n\tpublic class ");
            
            #line 35 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelInfo.GeneratedModelTypeName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 35 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelInfo.ModelType.FullName));
            
            #line default
            #line hidden
            this.Write(", IGeneratedModel\r\n\t{\r\n\t\tpublic ");
            
            #line 37 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelInfo.GeneratedModelTypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\t// Initially set to true so new instances don\'t try to load objects \r" +
                    "\n\t\t\t// that clearly won\'t be there. When LoadModel returns one of these\r\n\t\t\t// i" +
                    "t will set this property to false.\r\n");
            
            #line 42 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

var baseModelInfos = getModelInfoStack();

var addedMembers = new List<string>();

while (baseModelInfos.Count > 0)
{
	var modelInfo = baseModelInfos.Pop();

	if (modelInfo.Members
		.Where(m => m.Relation is DbRelation.ManyToOneAttribute)
		.Where(m => m.Relation.LoadOnDemand)
		.Where(m => !addedMembers.Contains(m.Name))
		.Any())
	{
		WriteLine("\t\t\t");
		WriteLine("\t\t\t// {0}", modelInfo.ModelType.Name);
	}

	foreach (DbMemberInfo member in modelInfo.Members
		.Where(m => m.Relation is DbRelation.ManyToOneAttribute)
		.Where(m => m.Relation.LoadOnDemand)
		.Where(m => !addedMembers.Contains(m.Name)))
	{
		WriteLine("\t\t\t_Support.HasMemberLoaded[\"{0}\"] = true;", member.Name);
	
		DbRelation.ManyToOneAttribute manyToOne = (DbRelation.ManyToOneAttribute)member.Relation;
	
		DbMemberInfo foreignMember = DbModelInfo.Get(manyToOne.ForeignType).ID;
	
		IDbModelInfo foreignModelInfo = DbModelInfo.Get(manyToOne.ForeignType);
	
		string backingMemberName = member.Name + foreignModelInfo.ID.Name;

		WriteLine("\t\t\t_Support.ObjectIds[\"{0}\"] = default({1});", backingMemberName, foreignMember.MemberType.FullName);
	}
}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tprivate ModelSupport __support = new ModelSupport();\r\n\t\tpublic ModelSupp" +
                    "ort _Support\r\n\t\t{\r\n\t\t\tget { return __support; }\r\n\t\t\tset { __support = value; }\r\n" +
                    "\t\t}\r\n");
            
            #line 88 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

baseModelInfos = getModelInfoStack();
addedMembers = new List<string>();

while (baseModelInfos.Count > 0)
{
	var modelInfo = baseModelInfos.Pop();

	if (modelInfo.Members.Any(m => m.Relation == null))
	{
		WriteLine("\t\t");
		WriteLine("\t\t// ---------- {0} ----------", modelInfo.ModelType.Name);
		WriteLine("\t\t");
	}

	foreach (DbMemberInfo member in modelInfo.Members
		.Where(m => m.Relation == null)
		.Where(m => !addedMembers.Contains(m.Name)))
	{
		string memberModifiers = " ";
		string backingMemberName = "";
	
		if (!ModelInfo.ModelType.IsInterface)
		{
			backingMemberName = "base." + member.Name;

			if (member.IsVirtual)
			{
				memberModifiers = "override ";
			}
			else
			{
				memberModifiers = "new ";
			}
		}

		if (ModelInfo.ModelType.IsInterface || member.IsAbstract)
		{
			backingMemberName = member.Name.ToCamelCase();
			WriteLine("\t\tprivate " + member.MemberType.FullName + " " + backingMemberName + ";");
		}

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 130 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(memberModifiers + member.MemberType.FullName + " " + member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\treturn ");
            
            #line 134 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value == ");
            
            #line 138 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t{\r\n\t\t\t\t\treturn;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\t");
            
            #line 143 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\r\n\t\t\t\t_Support.FieldChanged(\"");
            
            #line 145 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t}\r\n\t\t}\r\n\r\n");
            
            #line 149 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

	}


            
            #line default
            #line hidden
            this.Write("\t\t\r\n");
            
            #line 154 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

	foreach (DbMemberInfo member in modelInfo.Members
		.Where(m => m.Relation is DbRelation.ManyToOneAttribute)
		.Where(m => m.Relation.LoadOnDemand)
		.Where(m => !addedMembers.Contains(m.Name)))
	{
		DbRelation.ManyToOneAttribute manyToOne = (DbRelation.ManyToOneAttribute)member.Relation;
	
		DbMemberInfo foreignMember = DbModelInfo.Get(manyToOne.ForeignType).ID;
	
		IDbModelInfo foreignModelInfo = DbModelInfo.Get(manyToOne.ForeignType);
	
		string backingMemberName = member.Name + foreignModelInfo.ID.Name;

            
            #line default
            #line hidden
            this.Write("\t\tpublic override ");
            
            #line 168 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MemberType.FullName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 168 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tif (_Support.HasMemberLoaded[\"");
            
            #line 172 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"])\r\n\t\t\t\t{\r\n\t\t\t\t\tusing (var db = this._Support.CreateConnection())\r\n\t\t\t\t\t{\r\n\t\t\t\t\t" +
                    "\tbase.");
            
            #line 176 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = db.LoadModelById<");
            
            #line 176 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.MemberType.FullName));
            
            #line default
            #line hidden
            this.Write(">(_Support.ObjectIds[\"");
            
            #line 176 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write("\"]);\r\n\t\t\t\t\t}\r\n\t\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 178 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\treturn base.");
            
            #line 181 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value == null)\r\n\t\t\t\t{\r\n\t\t\t\t\t_Support.ObjectIds[\"");
            
            #line 187 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write("\"] = default(");
            
            #line 187 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignMember.MemberType.FullName));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\t\t}\r\n\t\t\t\telse\r\n\t\t\t\t{\r\n\t\t\t\t\t_Support.ObjectIds[\"");
            
            #line 191 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write("\"] = value.");
            
            #line 191 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignMember.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\tbase.");
            
            #line 194 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t\r\n\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 196 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 199 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

	}

	foreach (IDbMemberInfo member in modelInfo.Members
		.Where(m => m.Relation is DbRelation.OneToManyAttribute)
		.Where(m => m.Relation.LoadOnDemand)
		.Where(m => !addedMembers.Contains(m.Name)))
	{
		string backingMemberName = 
			member.Name.ToLower().Substring(0, 1) +
			member.Name.ToLower().Substring(1);

		string foreignFieldName = member.Relation.FieldName;

            
            #line default
            #line hidden
            this.Write("\t\tprivate List<");
            
            #line 213 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 213 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\r\n\t\tpublic override List<");
            
            #line 215 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 215 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tif (!_Support.HasMemberLoaded[\"");
            
            #line 219 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"])\r\n\t\t\t\t{\r\n\t\t\t\t\tusing (var db = this._Support.CreateConnection())\r\n\t\t\t\t\t{\r\n\t\t\t\t\t" +
                    "\t");
            
            #line 223 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(" = db.LoadModels<");
            
            #line 223 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write(">(\r\n\t\t\t\t\t\t\tnew LoadOptions()\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tWhere = \"");
            
            #line 226 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignFieldName));
            
            #line default
            #line hidden
            this.Write(" = @");
            
            #line 226 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignFieldName));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t\t\t\t\tParamValues = new object[] { ");
            
            #line 227 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelInfo.ID.Name));
            
            #line default
            #line hidden
            this.Write(" } \r\n\t\t\t\t\t\t\t}).ToList();\r\n\t\t\t\t\t}\r\n\t\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 230 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\treturn ");
            
            #line 233 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value == null)\r\n\t\t\t\t{\r\n\t\t\t\t\tif (_Support.HasMember" +
                    "Loaded[\"");
            
            #line 239 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"])\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");
            
            #line 241 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(".Clear();\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\telse\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 246 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 249 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 252 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

	}


	foreach (IDbMemberInfo member in modelInfo.Members
		.Where(m => m.Relation is DbRelation.ManyToManyAttribute)
		.Where(m => m.Relation.LoadOnDemand)
		.Where(m => !addedMembers.Contains(m.Name)))
	{
		string backingMemberName = 
			member.Name.ToLower().Substring(0, 1) +
			member.Name.ToLower().Substring(1);

		DbRelation.ManyToManyAttribute manyToMany = member.Relation as DbRelation.ManyToManyAttribute;

		IDbModelInfo foreignModelInfo = DbModelInfo.Get(manyToMany.ForeignType);

            
            #line default
            #line hidden
            this.Write("\t\tprivate List<");
            
            #line 269 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 269 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\r\n\t\tpublic override List<");
            
            #line 271 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 271 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t{\r\n\t\t\tget\r\n\t\t\t{\r\n\t\t\t\tif (!_Support.HasMemberLoaded[\"");
            
            #line 275 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"])\r\n\t\t\t\t{\r\n\t\t\t\t\tusing (var db = this._Support.CreateConnection())\r\n\t\t\t\t\t{\r\n\t\t\t\t\t" +
                    "\t");
            
            #line 279 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(" = db.LoadModels<");
            
            #line 279 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Relation.ForeignType.FullName));
            
            #line default
            #line hidden
            this.Write(">(\r\n\t\t\t\t\t\t\tnew LoadOptions()\r\n\t\t\t\t\t\t\t{\r\n\t\t\t\t\t\t\t\tJoins = \"");
            
            #line 282 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Format("JOIN {0} ON {0}.{1} = {2}.{3}",
									manyToMany.TableName,
									manyToMany.ForeignKey2,
									foreignModelInfo.TableName,
									foreignModelInfo.ID.FieldName)));
            
            #line default
            #line hidden
            this.Write("\",\r\n\r\n\t\t\t\t\t\t\t\tWhere = \"");
            
            #line 288 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(manyToMany.TableName + "." + manyToMany.ForeignKey1));
            
            #line default
            #line hidden
            this.Write(" = @");
            
            #line 288 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(manyToMany.ForeignKey1));
            
            #line default
            #line hidden
            this.Write("\",\r\n\r\n\t\t\t\t\t\t\t\tParamValues = new object[] { ");
            
            #line 290 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelInfo.ID.Name));
            
            #line default
            #line hidden
            this.Write(" }\r\n\t\t\t\t\t\t\t}).ToList();\r\n\t\t\t\t\t}\r\n\t\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 293 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\treturn ");
            
            #line 296 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t\t}\r\n\t\t\tset\r\n\t\t\t{\r\n\t\t\t\tif (value == null)\r\n\t\t\t\t{\r\n\t\t\t\t\tif (_Support.HasMember" +
                    "Loaded[\"");
            
            #line 302 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"])\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\t");
            
            #line 304 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(".Clear();\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\telse\r\n\t\t\t\t{\r\n\t\t\t\t\t");
            
            #line 309 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(backingMemberName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t\t\t\t}\r\n\t\t\t\t\r\n\t\t\t\t_Support.HasMemberLoaded[\"");
            
            #line 312 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(member.Name));
            
            #line default
            #line hidden
            this.Write("\"] = true;\r\n\t\t\t}\r\n\t\t}\r\n");
            
            #line 315 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

	}
	
	foreach (var member in modelInfo.Members)
	{
		addedMembers.Add(member.Name);
	}
}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\Ben Daniel\Documents\Projects\Libraries\Persisto\Templates\GeneratedModelTemplate.tt"

private global::Persisto.IDbModelInfo _ModelInfoField;

/// <summary>
/// Access the ModelInfo parameter of the template.
/// </summary>
private global::Persisto.IDbModelInfo ModelInfo
{
    get
    {
        return this._ModelInfoField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelInfoValueAcquired = false;
if (this.Session.ContainsKey("ModelInfo"))
{
    if ((typeof(global::Persisto.IDbModelInfo).IsAssignableFrom(this.Session["ModelInfo"].GetType()) == false))
    {
        this.Error("The type \'Persisto.IDbModelInfo\' of the parameter \'ModelInfo\' did not match the t" +
                "ype of the data passed to the template.");
    }
    else
    {
        this._ModelInfoField = ((global::Persisto.IDbModelInfo)(this.Session["ModelInfo"]));
        ModelInfoValueAcquired = true;
    }
}
if ((ModelInfoValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ModelInfo");
    if ((data != null))
    {
        if ((typeof(global::Persisto.IDbModelInfo).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'Persisto.IDbModelInfo\' of the parameter \'ModelInfo\' did not match the t" +
                    "ype of the data passed to the template.");
        }
        else
        {
            this._ModelInfoField = ((global::Persisto.IDbModelInfo)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class GeneratedModelTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
